[package]
name = "totp-cli"
version = "0.1.0"
authors = ["Tomoki Aonuma <uasi@uasi.jp>"]
edition = "2018"

[dependencies]
base32 = "0.4.0"
hmac = "0.6.0"
regex = "1.2.0"
sha-1 = "0.7.0"
toml = "0.5.1"
