[package]
name = "totp-cli"
version = "0.1.1"
authors = ["Tomoki Aonuma <uasi@uasi.jp>"]
edition = "2018"

[dependencies]
base32 = "0.4.0"
hmac = "0.10.1"
regex = "1.4.2"
sha-1 = "0.9.2"
toml = "0.5.1"
